---
- name: "Check for akhq jar file"
  ansible.builtin.stat:
    path: "{{ akhq_install_dir }}/akhq.jar"
  changed_when: false
  register: akhq_install

- name: "Get current version"
  ansible.builtin.shell: |
    set -o pipefail
    grep @version /etc/akhq/akhq.yml | awk '{print $NF}'
  args:
    executable: /bin/bash
  changed_when: false
  register: akhq_install_version
  when: akhq_install.stat.exists

- name: "Install tasks"
  when: (not akhq_install.stat.exists) or (akhq_install_version is defined and akhq_version not in akhq_install_version.stdout)
  block:
    - name: "Ensure install directory exists"
      ansible.builtin.file:
        path: '{{ akhq_install_dir }}'
        state: directory
        mode: '0755'

    - name: "Ensure configuration directory exists"
      ansible.builtin.file:
        path: '/etc/akhq/'
        state: directory
        mode: '0755'

    - name: "Install requierements"
      ansible.builtin.package:
        name: "ca-certificates"
        state: present
      register: pkg_result
      retries: 12
      delay: 10
      until: pkg_result is success

    - name: "Download akhq jar file..."
      ansible.builtin.get_url:
        url: '{{ akhq_jar_url }}'
        dest: "{{ akhq_install_dir }}/akhq.jar"
        timeout: 120
        mode: '0644'

- name: "Convert passwd with sha256"
  ansible.builtin.shell: |
    set -o pipefail
    echo -n "{{ akhq_admin_passwd }}" | sha256sum
  args:
    executable: /bin/bash
  register: akhq_pwd
  changed_when: false

- name: "Set variable password converted with sha256"
  ansible.builtin.set_fact:
    akhq_pwd_256: "{{ akhq_pwd.stdout.split(' ')[0] }}"

- name: "Create config file for akhq"
  ansible.builtin.template:
    src: akhq.yml.j2
    dest: /etc/akhq/akhq.yml
    mode: '0644'
  notify: "Restart akhq"

- name: "Create systemd init for akhq"
  ansible.builtin.template:
    src: akhq.service
    dest: /lib/systemd/system/
    mode: '0644'
  notify: "Restart akhq"

- name: "Start akhq.service"
  ansible.builtin.service:
    name: akhq
    state: started
    enabled: true
    daemon_reload: true
